# Generated by Django 4.0 on 2021-12-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('guest', '游客'), ('member', '会员'), ('volunteer', '志愿者'), ('director', '负责人'), ('administrator', '管理员')], default='member', max_length=13, verbose_name='角色'),
        ),
    ]
